# Path to source code
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**

# Go coverage report path
sonar.go.coverage.reportPaths=coverage.out

# Encoding of the source code
sonar.sourceEncoding=UTF-8
